apiVersion: v1
kind: Namespace
metadata:
   name: dev
   labels:
     name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: sc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      namespace: dev
      app: sc-demo
  template:
    metadata:
      labels:
         namespace: dev
         app: sc-demo
    spec:
      containers:
      - name: sc-demo
        image: reg.yulece.com/open/k8s:v-02
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sc-demo
  namespace: dev
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    namespace: dev
    app: sc-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name: sc-demo
spec:
  rules:
  - host: sc.yulece.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: sc-demo
          servicePort: 80
